name: daily
on:
  schedule:
    - cron: '00 06 * * *'
jobs:
  daily:
    name: daily
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo 'daily'
          echo 'daily'
          echo 'daily'
